// Generated by CoffeeScript 1.6.3
(function() {
  var LAYER_COUNT, MAX_WIDTH, MIN_SWIPE_DELAY, MIN_SWIPE_DISTANCE, MIN_TOUCH_DELAY, SWIPE_INCREMENT_X, drawAll, images, initController, tweets;

  MAX_WIDTH = 6000;

  MIN_SWIPE_DELAY = 1000;

  MIN_SWIPE_DISTANCE = 50;

  MIN_TOUCH_DELAY = 2000;

  SWIPE_INCREMENT_X = window.innerWidth;

  LAYER_COUNT = 1;

  images = null;

  tweets = [];

  $(function() {
    return drawAll();
  });

  drawAll = function() {
    var viewport, win;
    viewport = {
      x: 0,
      y: 0
    };
    win = {
      width: window.innerWidth,
      height: window.innerHeight
    };
    return initController(true, {
      onSwipeLeft: function() {
        return console.log('SWIPE LEFT');
      },
      onSwipeRight: function() {
        return console.log('SWIPE RIGHT');
      },
      onSwipeVertical: function() {
        console.log('SWIPE VERTICAL');
        return location.href = 'index.html';
      },
      onTouch: function(x, y) {}
    });
  };

  initController = function(autoConnect, api) {
    var controller, onSwipe, pointer, swiper, tSwipe, tTouch;
    controller = new Leap.Controller({
      enableGestures: true
    });
    console.log('Leap Motions start.');
    tSwipe = 0;
    onSwipe = function(data) {
      var tx, ty;
      if (Date.now() - tSwipe < MIN_SWIPE_DELAY) {
        return;
      }
      tSwipe = Date.now();
      tx = data.translation()[0];
      ty = data.translation()[1];
      if (Math.abs(tx) > MIN_SWIPE_DISTANCE) {
        if (tx > 0) {
          api.onSwipeLeft();
        } else {
          api.onSwipeRight();
        }
      }
      if (Math.abs(ty) > MIN_SWIPE_DISTANCE * 1.5) {
        return api.onSwipeVertical();
      }
    };
    swiper = controller.gesture('swipe').update(onSwipe);
    tTouch = 0;
    pointer = $('#pointer');
    controller.on('frame', function(frame) {
      var finger, s, x, y, _ref;
      finger = (_ref = frame.pointables) != null ? _ref[0] : void 0;
      if (finger == null) {
        return;
      }
      x = window.innerWidth / 2 + finger.tipPosition[0] * 7;
      y = window.innerHeight - finger.tipPosition[1] * 5 + 250;
      s = finger.tipPosition[2] / 60;
      pointer.css('transform', "translate3d(" + x + "px, " + y + "px, 0px) scale(" + s + ", " + s + ")");
      if (finger.tipPosition[2] < 0) {
        if (Date.now() - tTouch > MIN_TOUCH_DELAY) {
          tTouch = Date.now();
          pointer.hide();
          setTimeout((function() {
            api.onTouch(x, y);
            return pointer.show();
          }), 0);
        }
      }
    });
    controller.on('connect', function() {
      return console.log('Leap Motion Server connected.');
    });
    controller.on('disconnect', function() {
      return console.log('Leap Motion Server disconnected.');
    });
    controller.on('deviceConnect', function() {
      return console.log('Leap Motion connected.');
    });
    controller.on('deviceDisconnect', function() {
      return console.log('Leap Motion disconnected.');
    });
    if (autoConnect) {
      return controller.connect();
    }
  };

}).call(this);
