// Generated by CoffeeScript 1.6.3
(function() {
  var createImage;

  $(function() {
    var h, i, images, layer, stage, url, w, win, x, y, _i, _results;
    win = {
      width: window.innerWidth,
      height: window.innerHeight
    };
    stage = new Kinetic.Stage({
      container: 'main',
      width: win.width,
      height: win.height
    });
    layer = new Kinetic.Layer();
    images = [];
    _results = [];
    for (i = _i = 0; _i <= 20; i = ++_i) {
      w = Math.round(Math.random() * 400);
      h = Math.round(Math.random() * 400);
      x = Math.round(Math.random() * 400);
      y = Math.round(Math.random() * 400);
      url = "http://placekitten.com/" + w + "/" + h;
      _results.push(images.push(createImage(url, w, h)));
    }
    return _results;
  });

  createImage = function(url, w, h, x, y) {
    var img;
    img = new Image();
    return img.onload = function() {};
  };

}).call(this);
